# Build Stage
FROM golang:1.11-alpine3.9 AS build

# Install tools required for project
# Run `docker build --no-cache .` to update dependencies
RUN apk add --no-cache git && go get github.com/golang/dep/cmd/dep

# List project dependencies with Gopkg.toml and Gopkg.lock
# These layers are only re-built when Gopkg files are updated
COPY Gopkg.lock Gopkg.toml /go/src/app/
WORKDIR /go/src/app/
# Install library dependencies
RUN dep ensure -vendor-only

# Build the application
COPY . /go/src/app
RUN go build -o bin/app

# Final Image
FROM alpine:3.9

RUN apk update && apk upgrade && \
  apk add --no-cache openssl ca-certificates

# Install tools required for project
RUN wget https://github.com/Droplr/aws-env/raw/master/bin/aws-env-linux-amd64 -O /bin/aws-env

COPY --from=build /go/src/app/bin /app/

RUN chmod +x /bin/aws-env
WORKDIR /app

CMD eval $(aws-env) && ./app