node('jnlp-slave'){
  stage('SCM') {
    git url: 'https://github.com/nclouds/generalized.git', branch: 'Layer2'
  }
  stage('Test') {
    sh 'ls'
    dir("cloudformation/ECS/continuous-integration/jenkins"){
      sh 'docker run --rm -i hadolint/hadolint hadolint --trusted-registry nclouds.com - < Dockerfile'
    }
  }
}
