name 'ops-caddy'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures ops-caddy'
long_description 'Installs/Configures ops-caddy'
version '0.1.0'
