name 'ops-jenkins'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures ops-jenkins'
long_description 'Installs/Configures ops-jenkins'
version '0.1.0'

depends 'apt'
depends 'java'
#depends 'ops-caddy'
#depends 'ops-docker'
depends 'jenkins'
depends 'ssh_known_hosts'
depends 'awscli'
#depends 'ops-base'
