name 'ops-icinga2'
maintainer 'Artem Kobrin'
maintainer_email 'artem@nclouds.com'
license 'all_rights'
description 'Installs/Configures icinga2'
long_description 'Installs/Configures icinga2'
version '0.1.0'

depends 'yum'
depends 'apt'
depends 'nrpe'
depends 'python'
#depends 'ops-base'
#depends 'ops-rabbitmq'
#depends 'ops-route53_autoupdate'
