#!/bin/bash

export PATH=/usr/local/bin:$PATH
end_time=`date +%Y-%m-%dT%H:%M:%S`
start_time=`date --date '-10 min' +%Y-%m-%dT%H:%M:%S`

for instance in "$@"; do
  average=`aws cloudwatch get-metric-statistics --metric-name ReadIOPS --start-time $start_time --end-time $end_time --period 60 --namespace AWS/RDS --statistics Average --dimensions Name=DBInstanceIdentifier,Value=$instance --region us-east-1 | jq -r '.Datapoints[]["Average"]' | head -n1`
  echo "ReadIOPS $instance | readiosps_$instance=$average"

  average=`aws cloudwatch get-metric-statistics --metric-name WriteIOPS --start-time $start_time --end-time $end_time --period 60 --namespace AWS/RDS --statistics Average --dimensions Name=DBInstanceIdentifier,Value=$instance --region us-east-1 | jq -r '.Datapoints[]["Average"]' | head -n1`
  echo "RDS $instance | writeiops_$instance=$average"
done
